CREATE TABLE LOYALTY_CARD(
    LOYALTY_CARD_ID INT PRIMARY KEY AUTO_INCREMENT,
    BARCODE VARCHAR(20),
    BONUS_POINTS INT);

ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_LOYALTY_CARD
    FOREIGN KEY (LOYALTY_CARD_ID)
    REFERENCES LOYALTY_CARD(LOYALTY_CARD_ID);